### ISSUE TITLE
anhalytics_metadatateis index

### ISSUE THREAD

**Issue by kermitt2** [anHALytics/anhalytics-core#78]
What is the purpose of anhalytics_metadatateis index, given that anhalytics_fulltextteis should also contain all the metadata?

Good to note: in the indexing of anhalytics_metadatateis, the application of the IndexingPreprocess will  inject all the searchable annotations to these documents, which is probably not what is expected.

**Comment by Aazhar** [comment]
The purpose of having both was due to the kb construction, because mining and indexing only those with the fulltext leads to biased graphics..

**Comment by Aazhar** [comment]
From this 684f521 and on, not distinction should be done between those with or without fulltext.

**Comment by kermitt2** [comment]
Does it mean that we are working only with full text or that the KB construction is not using anymore an ElasticSearch index?

**Comment by Aazhar** [comment]
At the beginning (for demo reasons I think and also because we were using only HAL) we were basically considering only teis having an associated fulltext TEI for the whole pipeline, but for now since we are making the process more generic(and also because in ISTEX there is a good fulltext coverage) no distinction is made between those with or without fulltext, but could be easily done if needed using the biblioObject attribut(isWithFulltext).

**Comment by kermitt2** [comment]
Thanks !
Just as side note, there is 100% full text in ISTEX.
